ADDREQ =(
    'REQUEST_METHOD',
    'REMOTE_ADDR',
    'REMOTE_HOST',
    'CONTENT_TYPE',
    'CSRF_COOKIE',
    'SERVER_SOFTWARE',
    'SERVER_PROTOCOL',
    'CONTENT_LENGTH',
    'SERVER_PORT',
    'SERVER_NAME',
)