# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-04-18 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.UUIDField(auto_created=True, default='898d33ce0de8474aa0275c3e85cd0ab9', editable=False, primary_key=True, serialize=False),
        ),
    ]
